language: node_js
node_js:
  - '0.10'
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
install:
    - gem install compass
    - npm install -g bower grunt-cli
    - npm install
    - bower cache clean
    - bower install
before_script:
    - cp app/scripts/config.js.example app/scripts/config.js
script:
  - npm test
  - ./node_modules/.bin/grunt jshint
